version: '3.8'

services:
  blue:
    build:
      context: ..
      dockerfile: docker/blue/Dockerfile
    container_name: quote-generator-blue
    ports:
      - "8081:3000"
    environment:
      - PORT=3000
      - DEPLOYMENT_COLOR=blue
      - VERSION=v1.0.0
    networks:
      - quote-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  green:
    build:
      context: ..
      dockerfile: docker/green/Dockerfile
    container_name: quote-generator-green
    ports:
      - "8082:3000"
    environment:
      - PORT=3000
      - DEPLOYMENT_COLOR=green
      - VERSION=v1.1.0
    networks:
      - quote-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:stable-alpine
    container_name: quote-generator-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blue
      - green
    networks:
      - quote-network
    restart: unless-stopped

networks:
  quote-network:
    driver: bridge